/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_liuxiaobai_TeaJniNative */

#ifndef _Included_com_liuxiaobai_TeaJniNative
#define _Included_com_liuxiaobai_TeaJniNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_liuxiaobai_TeaJniNative
 * Method:    encrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_liuxiaobai_TeaJniNative_encrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_liuxiaobai_TeaJniNative
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_liuxiaobai_TeaJniNative_decrypt
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif